version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
